object Dependencies {

    val kotlinCore =  "org.jetbrains.kotlin:kotlin-stdlib:${DependenciesVersions.kotlinVersion}"
    val kotlinKtx =  "androidx.core:core-ktx:${DependenciesVersions.kotlinKtxVersion}"
    val appCompat = "androidx.appcompat:appcompat:${DependenciesVersions.appCompatVersion}"
    val googleMaterial = "com.google.android.material:material:${DependenciesVersions.googleMaterialVersion}"
    val constraintLayout =  "androidx.constraintlayout:constraintlayout:2.1.0"
    val swipeToRefresh = "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
    val navigationFragmentKtx =  "androidx.navigation:navigation-fragment-ktx:${DependenciesVersions.navigationComponentVersion}"
    val navigationUiKtx = "androidx.navigation:navigation-ui-ktx:${DependenciesVersions.navigationComponentVersion}"
    val retrofit = "com.squareup.retrofit2:retrofit:${DependenciesVersions.retrofitVersion}"
    val retrofitGsonConverter ="com.squareup.retrofit2:converter-gson:${DependenciesVersions.retrofitVersion}"
    val roomCore = "androidx.room:room-runtime:${DependenciesVersions.roomVersion}"
    val roomKapt = "androidx.room:room-compiler:${DependenciesVersions.roomVersion}"
    val roomKtx =  "androidx.room:room-ktx:${DependenciesVersions.roomVersion}"
    val liveData = "androidx.lifecycle:lifecycle-livedata-ktx:2.3.1"
    val coroutinesCore = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${DependenciesVersions.coroutinesVersion}"
    val coroutinesAndroid = "org.jetbrains.kotlinx:kotlinx-coroutines-android:${DependenciesVersions.coroutinesVersion}"
    val hiltCore = "com.google.dagger:hilt-android:${DependenciesVersions.hiltVersion}"
    val hiltKapt = "com.google.dagger:hilt-android-compiler:${DependenciesVersions.hiltVersion}"
    val coroutinesTest = "org.jetbrains.kotlinx:kotlinx-coroutines-test:${DependenciesVersions.coroutinesVersion}"
    val junitTest = "androidx.test.ext:junit:1.1.2"
    val espressoCore = "androidx.test.espresso:espresso-core:3.3.0"
    val googleTruth =  "com.google.truth:truth:1.1.2"
    val coreTesting = "androidx.arch.core:core-testing:2.1.0"
    val mockk = "io.mockk:mockk:1.10.6"
    val workManagerTesting = "androidx.work:work-testing:2.5.0"
    val workManager = "androidx.work:work-runtime-ktx:${DependenciesVersions.workManagerVersion}"
    val hiltWorkManager = "androidx.hilt:hilt-work:1.0.0-beta01"
    val hiltKaptAndroidx = "androidx.hilt:hilt-compiler:1.0.0-beta01"
    val settings =  "androidx.preference:preference-ktx:${DependenciesVersions.settingsVersion}"
    val charts = "com.github.PhilJay:MPAndroidChart:v3.1.0"
    val rssParser = "com.prof18.rssparser:rssparser:3.1.4"
    val shimmer = "com.facebook.shimmer:shimmer:0.5.0"
    val shimmerRecyclerView = "com.todkars:shimmer-recyclerview:0.4.0"
    val searchableSpinner = "com.toptoche.searchablespinner:searchablespinnerlibrary:1.3.1"
    val glideCore = "com.github.bumptech.glide:glide:${DependenciesVersions.glideVersion}"
    val glideKapt = "com.github.bumptech.glide:compiler:${DependenciesVersions.glideVersion}"

}